- name: Install packages
  ansible.builtin.apt:
    pkg:
      - postgresql-common
      - python3-pip
      - python3-dev
      - python3-psycopg2
      - libpq-dev
      - gcc
    update_cache: true
- name: disbable initializing of default postgres cluster
  ansible.builtin.replace:
    path: /etc/postgresql-common/createcluster.conf
    replace: create_main_cluster = false
    regexp: ^#?create_main_cluster.*$
- name: install postgres
  ansible.builtin.apt:
    pkg:
      - postgresql
      - postgresql-client
- name: install python lib
  ansible.builtin.pip:
    name:
      - patroni
      - python-etcd
- name: patroni directory
  ansible.builtin.file:
    path: /etc/patroni
    state: directory
    owner: root
    group: root
    mode: 0655

- name: patroni template
  ansible.builtin.template:
    src: 'patroni.yaml.j2'
    dest: /etc/patroni/patroni.yml
    owner: root
    group: root
    mode: '0644'
- name: create data directory
  ansible.builtin.file:
    path: '{{ patroni_data_dir }}'
    owner: postgres
    group: postgres
    state: directory
    recurse: yes
    mode: '0700'
- name: copy service file
  ansible.builtin.copy:
    src: 'patroni.service'
    dest: /etc/systemd/system/patroni.service
    mode: 0755
- name: start patroni
  ansible.builtin.systemd:
    name: patroni
    state: started
    enabled: yes
