- name: Install packages
  apt:
    pkg:
      - postgresql-common
      - python3-pip
      - python3-dev
      - python3-psycopg2
      - libpq-dev
      - gcc
    update_cache: true
- name: disbable initializing of default postgres cluster
  replace:
    path: /etc/postgresql-common/createcluster.conf
    replace: create_main_cluster = false
    regexp: ^#?create_main_cluster.*$
- name: install postgres
  apt:
    pkg:
      - postgresql
      - postgresql-client
- name: install python lib
  pip:
    name:
      - patroni
      - python-etcd
- name: patroni directory
  file:
    path: /etc/patroni
    state: directory
    owner: root
    group: root
    mode: 0655

- name: patroni template
  template:
    src: 'patroni.yaml.j2'
    dest: /etc/patroni/patroni.yml
    owner: root
    group: root
    mode: '0644'
- name: create data directory
  file:
    path: '{{ patroni_data_dir }}'
    owner: postgres
    group: postgres
    state: directory
    recurse: yes
    mode: '0700'
- name: copy service file
  copy:
    src: 'patroni.service'
    dest: /etc/systemd/system/patroni.service
    mode: 0755
- name: start patroni
  systemd:
    name: patroni
    state: started
    enabled: yes
